### YamlMime:ManagedReference
items:
- uid: ConsoleGit.ConfiguredHttpClient
  commentId: N:ConsoleGit.ConfiguredHttpClient
  id: ConsoleGit.ConfiguredHttpClient
  children:
  - ConsoleGit.ConfiguredHttpClient.LoginHandler
  - ConsoleGit.ConfiguredHttpClient.LoginRequest
  - ConsoleGit.ConfiguredHttpClient.MyHandler
  langs:
  - csharp
  - vb
  name: ConsoleGit.ConfiguredHttpClient
  nameWithType: ConsoleGit.ConfiguredHttpClient
  fullName: ConsoleGit.ConfiguredHttpClient
  type: Namespace
  assemblies:
  - ConsoleGit
references:
- uid: ConsoleGit.ConfiguredHttpClient.LoginHandler
  commentId: T:ConsoleGit.ConfiguredHttpClient.LoginHandler
  href: ConsoleGit.ConfiguredHttpClient.LoginHandler.html
  name: LoginHandler
  nameWithType: LoginHandler
  fullName: ConsoleGit.ConfiguredHttpClient.LoginHandler
- uid: ConsoleGit.ConfiguredHttpClient.LoginRequest
  commentId: T:ConsoleGit.ConfiguredHttpClient.LoginRequest
  href: ConsoleGit.ConfiguredHttpClient.LoginRequest.html
  name: LoginRequest
  nameWithType: LoginRequest
  fullName: ConsoleGit.ConfiguredHttpClient.LoginRequest
- uid: ConsoleGit.ConfiguredHttpClient.MyHandler
  commentId: T:ConsoleGit.ConfiguredHttpClient.MyHandler
  href: ConsoleGit.ConfiguredHttpClient.MyHandler.html
  name: MyHandler
  nameWithType: MyHandler
  fullName: ConsoleGit.ConfiguredHttpClient.MyHandler
