### YamlMime:ManagedReference
items:
- uid: Terrasoft.Configuration.InstallConsoleGitInstallScript
  commentId: T:Terrasoft.Configuration.InstallConsoleGitInstallScript
  id: InstallConsoleGitInstallScript
  parent: Terrasoft.Configuration
  children:
  - Terrasoft.Configuration.InstallConsoleGitInstallScript.Execute(Terrasoft.Core.UserConnection)
  langs:
  - csharp
  - vb
  name: InstallConsoleGitInstallScript
  nameWithType: InstallConsoleGitInstallScript
  fullName: Terrasoft.Configuration.InstallConsoleGitInstallScript
  type: Class
  source:
    remote:
      path: packages/AtfTIDE/Schemas/InstallConsoleGitInstallScript/InstallConsoleGitInstallScript.cs
      branch: main
      repo: https://github.com/Advance-Technologies-Foundation/T.I.D.E..git
    id: InstallConsoleGitInstallScript
    path: ../packages/AtfTIDE/Schemas/InstallConsoleGitInstallScript/InstallConsoleGitInstallScript.cs
    startLine: 11
  assemblies:
  - AtfTIDE
  namespace: Terrasoft.Configuration
  syntax:
    content: 'public class InstallConsoleGitInstallScript : IInstallScriptExecutor'
    content.vb: Public Class InstallConsoleGitInstallScript Implements IInstallScriptExecutor
  inheritance:
  - System.Object
  implements:
  - Terrasoft.Core.IInstallScriptExecutor
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Terrasoft.Configuration.InstallConsoleGitInstallScript.Execute(Terrasoft.Core.UserConnection)
  commentId: M:Terrasoft.Configuration.InstallConsoleGitInstallScript.Execute(Terrasoft.Core.UserConnection)
  id: Execute(Terrasoft.Core.UserConnection)
  parent: Terrasoft.Configuration.InstallConsoleGitInstallScript
  langs:
  - csharp
  - vb
  name: Execute(UserConnection)
  nameWithType: InstallConsoleGitInstallScript.Execute(UserConnection)
  fullName: Terrasoft.Configuration.InstallConsoleGitInstallScript.Execute(Terrasoft.Core.UserConnection)
  type: Method
  source:
    remote:
      path: packages/AtfTIDE/Schemas/InstallConsoleGitInstallScript/InstallConsoleGitInstallScript.cs
      branch: main
      repo: https://github.com/Advance-Technologies-Foundation/T.I.D.E..git
    id: Execute
    path: ../packages/AtfTIDE/Schemas/InstallConsoleGitInstallScript/InstallConsoleGitInstallScript.cs
    startLine: 12
  assemblies:
  - AtfTIDE
  namespace: Terrasoft.Configuration
  summary: Executes package install script.
  example: []
  syntax:
    content: public void Execute(UserConnection userConnection)
    parameters:
    - id: userConnection
      type: Terrasoft.Core.UserConnection
      description: User connection.
    content.vb: Public Sub Execute(userConnection As UserConnection)
  overload: Terrasoft.Configuration.InstallConsoleGitInstallScript.Execute*
  implements:
  - Terrasoft.Core.IInstallScriptExecutor.Execute(Terrasoft.Core.UserConnection)
references:
- uid: Terrasoft.Configuration
  commentId: N:Terrasoft.Configuration
  href: Terrasoft.html
  name: Terrasoft.Configuration
  nameWithType: Terrasoft.Configuration
  fullName: Terrasoft.Configuration
  spec.csharp:
  - uid: Terrasoft
    name: Terrasoft
    href: Terrasoft.html
  - name: .
  - uid: Terrasoft.Configuration
    name: Configuration
    href: Terrasoft.Configuration.html
  spec.vb:
  - uid: Terrasoft
    name: Terrasoft
    href: Terrasoft.html
  - name: .
  - uid: Terrasoft.Configuration
    name: Configuration
    href: Terrasoft.Configuration.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: Terrasoft.Core.IInstallScriptExecutor
  commentId: T:Terrasoft.Core.IInstallScriptExecutor
  parent: Terrasoft.Core
  isExternal: true
  name: IInstallScriptExecutor
  nameWithType: IInstallScriptExecutor
  fullName: Terrasoft.Core.IInstallScriptExecutor
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Terrasoft.Core
  commentId: N:Terrasoft.Core
  isExternal: true
  name: Terrasoft.Core
  nameWithType: Terrasoft.Core
  fullName: Terrasoft.Core
  spec.csharp:
  - uid: Terrasoft
    name: Terrasoft
    isExternal: true
  - name: .
  - uid: Terrasoft.Core
    name: Core
    isExternal: true
  spec.vb:
  - uid: Terrasoft
    name: Terrasoft
    isExternal: true
  - name: .
  - uid: Terrasoft.Core
    name: Core
    isExternal: true
- uid: Terrasoft.Configuration.InstallConsoleGitInstallScript.Execute*
  commentId: Overload:Terrasoft.Configuration.InstallConsoleGitInstallScript.Execute
  href: Terrasoft.Configuration.InstallConsoleGitInstallScript.html#Terrasoft_Configuration_InstallConsoleGitInstallScript_Execute_Terrasoft_Core_UserConnection_
  name: Execute
  nameWithType: InstallConsoleGitInstallScript.Execute
  fullName: Terrasoft.Configuration.InstallConsoleGitInstallScript.Execute
- uid: Terrasoft.Core.IInstallScriptExecutor.Execute(Terrasoft.Core.UserConnection)
  commentId: M:Terrasoft.Core.IInstallScriptExecutor.Execute(Terrasoft.Core.UserConnection)
  parent: Terrasoft.Core.IInstallScriptExecutor
  isExternal: true
  name: Execute(UserConnection)
  nameWithType: IInstallScriptExecutor.Execute(UserConnection)
  fullName: Terrasoft.Core.IInstallScriptExecutor.Execute(Terrasoft.Core.UserConnection)
  spec.csharp:
  - uid: Terrasoft.Core.IInstallScriptExecutor.Execute(Terrasoft.Core.UserConnection)
    name: Execute
    isExternal: true
  - name: (
  - uid: Terrasoft.Core.UserConnection
    name: UserConnection
    isExternal: true
  - name: )
  spec.vb:
  - uid: Terrasoft.Core.IInstallScriptExecutor.Execute(Terrasoft.Core.UserConnection)
    name: Execute
    isExternal: true
  - name: (
  - uid: Terrasoft.Core.UserConnection
    name: UserConnection
    isExternal: true
  - name: )
- uid: Terrasoft.Core.UserConnection
  commentId: T:Terrasoft.Core.UserConnection
  parent: Terrasoft.Core
  isExternal: true
  name: UserConnection
  nameWithType: UserConnection
  fullName: Terrasoft.Core.UserConnection
