name: release-to-nuget

on:
  release:
    types: [published]

jobs:
  build:
    name: release-to-nuget
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Pack
        run: dotnet pack .\packages\AtfTIDE\Files\AtfTIDE.csproj --configuration Release --output ./output

      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.CLIO_NUGET_API_KEY }}
        run: dotnet nuget push ".\output\*.nupkg" --api-key ${{ secrets.CLIO_NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
